    <cfset option.business = "wes@fedttw.com"> 
    <cfset option.item_name = "subscription"> 
    <cfset option.a3 = "100"> 
    <cfset option.p3 = "12"> 
    <cfset option.t3 = "M">
    <cfset option.src = "1">
    <cfset option.srt = "12">
    <cfset option.sra = "1">
    <cfset option.custom = "custom">    
    <cfset option.invoice = "1">    
    <cfset option.modify = "2	">    
    <cfset option.usr_manage = "1"> 